services:
  haul-api:
    image: img-haul-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 6000:3000
      - 9229:9229
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: inspections
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5438:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
