FROM node:22.9-slim AS build-stage

RUN apt-get update && apt-get install -y procps

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --silent

COPY . .

EXPOSE 9229

EXPOSE 3000

CMD [ "yarn", "start:debug" ]
