name: Create pull request to production

on:
  push:
    branches:
      - staging

  workflow_dispatch:

env:
  DESTINATION_BRANCH: "main"

jobs:
  create-pull-request:
    name: Create pull request to production
    runs-on:
      - ubuntu-latest
    container:
      image: docker:19.03-git
    steps:
      - uses: actions/checkout@v2

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ env.DESTINATION_BRANCH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Deploy to Production"
          pr_draft: true
          pr_allow_empty: false
